# Laboratorio 1 Python

## <a id='1.0'> 1.0 Types of variables  </a> 


In [ ]:
#En el espacio de cuadro: no dentro del código

# Crtl + Enter  correr
# B             añadir linea de codigo
# DD            borrar linea de codigo
# Z             recuperar

# (seleccionar):
# Crtl +  /                pasar de código a comentario (vicev)
# Shift + M                unir celdas de codigo
# Crtl  + Shift + -        dividir celdas de codigo
#  Shift + tecla ↑↓        seleccionar varias líneas de codigo  

In [4]:
a1 = 3.141
type(a1)

# from float to int 

c = int(a1)

type(c)

b1 = 10000
type(b1)

float

In [7]:
# from int to float 

float(b1)  #para que tenga decimal

10000.0

In [10]:
b2 = 8
type(b2)

int

Variables tipos string: 

In [8]:


c1 = 'My first python code'  # "My first python code" usando doble comilla
print(c1)  # show that varaible's content OBSERVAR 
type(c1) # providing varaibles's type 

My first python code


str

In [9]:
# including a space using \n

c1 = "First python code"
c2 = "at R y python Class"
print(c1,'\n',c2)   # \n es para ser abajo

First python code 
 at R y python Class


In [20]:
# join string 

print(c1 + " : " + c2)

First python code : at R y python Class


In [25]:
# f-string
    # crear un string llamando a un string
    # f'{es una variable string c1} ==> no hay coma
print(f'{c1} : semester 2022-1')

First python code : semester 2022-1


In [12]:
d = 2022

print(f'{c1} : semester {d}-1')

First python code : semester 2022-1


In [23]:
print('{} : semester {}-1'.format(c1,d))  #???

First python code : semester 2022-1


In [25]:
# Substr elements from string
  # no se vio
c1[0:5]

'First'

In [17]:
#first character
print('Fisrt letter is :',c1[0])

Fisrt letter is : F


In [35]:
#first word
print('Fisrt word is :',c1[0:5])

Fisrt word is : First


## <a id='1.2'> 1.2 Boolean  </a> 

It’s used to represent the truth value of an expression.

In [26]:
"a" == "a"

True

In [27]:
1 > 1

False

In [41]:
z1 = (1==1)  # z1 = (true) = true
z1 

True

In [43]:
int(z1)  # true is 1 in numerical system

1

In [28]:
z2 = (10 > 20) 
int(z2) # false is 0 in numerical system

0

## <a id='1.3'> 1.3 Tuple  </a> 

It is an ordered and immutable Python object, ES INMUTABLE

In [14]:
# Se define con ()
# Es inmutable

T1 = (1,4,8,10,20,15,4,5,3,8)

type(T1)

tuple

In [17]:
# aritmethic operations

print(' Suma:', sum(T1),"\n", "Minimo:", min(T1), '\n', "Maximo:", max(T1))

 Suma: 78 
 Minimo: 1 
 Maximo: 20


In [53]:
# numero de elementos

len(T1) # lenght of tuple

10

### Indexing Tuple

In [19]:
T1 = (1,4,8,10,20,15,4,5,3,8)

T1[0:5] # give us elements from 0 position until 4 position 

(1, 4, 8, 10, 20)

In [23]:
T1[0] # get tuple's element 

1

In [21]:
T1[0:3]


(1, 4, 8)

In [22]:
# It is not possible to change porque es una Tupla
T1[0] = 4   

TypeError: 'tuple' object does not support item assignment

In [70]:
#El último elemento
T1[-1]

8

In [68]:
#position 
    # de la tupla T1. indice(el numero 8) está en la posicion 2
T1.index(8)

2

## <a id='1.4'> 1.4 List  </a> 

#### It is an ordered and mutable Python container. Puede ser alterada.

In [24]:
L1 = []
print(L1)
type(L1)

[]


list

In [25]:
dis1 = ["ATE", 'BARRANCO','BREÑA', 'CALLAO', 'CARABAYLLO']
dis1

['ATE', 'BARRANCO', 'BREÑA', 'CALLAO', 'CARABAYLLO']

In [26]:
dis2 = ['ATE', 'BARRANCO','BREÑA', 'CALLAO', 'CARABAYLLO','CHACLACAYO','CHORRILLOS','CIENEGUILLA'
        ,'COMAS','EL_AGUSTINO','INDEPENDENCIA']

In [27]:
#Numero de elementos de lista

len(dis2)

11

In [39]:
#Se puede ALTERAR los elementos de la lista

dis2[0] = "CALLAO"
print(dis2)

['CALLAO', 'BARRANCO', 'BREÑA', 'CALLAO', 'CARABAYLLO', 'CHACLACAYO', 'CHORRILLOS', 'CIENEGUILLA', 'COMAS', 'EL_AGUSTINO', 'INDEPENDENCIA']


In [28]:
# Idenxing: Que aparezca elemento en posicion 1

dis2[1]

'BARRANCO'

In [29]:
dis2[2:5]   # (5-1=4)

['BREÑA', 'CALLAO', 'CARABAYLLO']

In [30]:
dis2[3:7]

['CALLAO', 'CARABAYLLO', 'CHACLACAYO', 'CHORRILLOS']

In [31]:
dis2[-5:-1]

['CHORRILLOS', 'CIENEGUILLA', 'COMAS', 'EL_AGUSTINO']

In [32]:
num = [13,5,5,8,9,10,5,8,13,1,20]
num.sort()
print(num)

[1, 5, 5, 5, 8, 8, 9, 10, 13, 13, 20]


In [33]:
# append new elements 
#AGREGAR ELEMENTOS A LISTA  = append

num.append(102)
print(num)

[1, 5, 5, 5, 8, 8, 9, 10, 13, 13, 20, 102]


In [34]:
# append new list
#AGREAGAR LISTA A LISTA = extend
num2 = [10,20,30]
num.extend(num2)
print(num)

[1, 5, 5, 5, 8, 8, 9, 10, 13, 13, 20, 102, 10, 20, 30]


In [35]:
print(num.index(102))

11


In [49]:
print("Suma:", sum(num),'\n', "Minimo:", min(num), '\n', "Maximo:", max(num))

Suma: 361 
 Minimo: 1 
 Maximo: 102


## <a id='1.5'> 1.5 Diccionario  </a> 

Hay un nombre y valor

{ keys: valor }


In [40]:
#  x = { 'Nombre etiqueta' : [x1 x2 x3], numero, string}

Postal_code = {'Majes': 40520, 'Mollendo': 40701, 'Islay': 40704, 'Cotahuasi': 40801, 'Alca': 40802 }
type(Postal_code)

dict

In [39]:
Postal_code

{'Majes': 40520,
 'Mollendo': 40701,
 'Islay': 40704,
 'Cotahuasi': 40801,
 'Alca': 40802}

In [41]:
Postal_code.keys()

dict_keys(['Majes', 'Mollendo', 'Islay', 'Cotahuasi', 'Alca'])

In [42]:
# Get information from key
Postal_code['Alca']

40802

In [43]:
# Get information from key
Postal_code.get('Alca')

40802

In [101]:
#Eliminar elemento llave + elemento 
#Drop key
Postal_code.pop('Islay')
Postal_code

{'Majes': 40520, 'Mollendo': 40701, 'Cotahuasi': 40801, 'Alca': 40802}

In [44]:
# add new elements 
    # llaves + elemento

Postal_code.update( { "CHARCANA" :  40803 } )

#diccioanrio dentro de otro diccionario
Postal_code.update( {"LOMAS": {"UBIGEO": 40311, "Poverty Rate" : "18.2%", "Population" : "20 mil"}})


In [45]:
Postal_code

{'Majes': 40520,
 'Mollendo': 40701,
 'Islay': 40704,
 'Cotahuasi': 40801,
 'Alca': 40802,
 'CHARCANA': 40803,
 'LOMAS': {'UBIGEO': 40311, 'Poverty Rate': '18.2%', 'Population': '20 mil'}}

In [61]:
Postal_code.get('LOMAS').get('Poverty Rate')

'18.2%'

In [46]:
# elemento dentro de llave:

Postal_code['LOMAS']['Poverty Rate']

'18.2%'

In [62]:
# keys
cities = ['Fray Martin','Santa Rosa de Puquio','Cuchicorral','Santiago de Punchauca','La Cruz (11 Amigos)','Cerro Cañon','Cabaña Suche','San Lorenzo','Jose Carlos Mariategui','Pascal','La Esperanza','Fundo Pancha Paula','Olfa','Rio Seco','Paraiso','El Rosario','Cerro Puquio','La Campana','Las Animas','Vetancio','Roma Alta','San Jose','San Pedro de Carabayllo','Huacoy','Fundo Pampa Libre','Ex Fundo Santa Ines','Reposo','Carmelito','Santa Elena','Don Luis','Santa Ines Parcela','Asociacion Santa Ines','Roma Baja','Residencial Santa Lucia','San Francisco','Santa Margarita - Molinos','Sipan Peru','Fundo Cuadros','Bello Horizonte','El Hueco','Ex Fundo Mariategui','Naranjito','Vista Hermosa','El Sabroso de Jose Carlos Mariategui','Granja Carabayllo','Agropecuario Valle el Chillon','Camino Real','Copacabana','El Trebol','Tablada la Virgen','San Fernando de Carabayllo','San Fernando de Copacabana','La Manzana','Chacra Grande','Torres de Copacabana','San Pedro de Carabayllo','San Lorenzo','Chaclacayo','Chorrillos','Cieneguilla','Lindero','Pichicato','San Isidro','San Vicente','Piedra Liza','Santa Rosa de Chontay (Chontay)','La Libertad','El Agustino','Independencia','Jesus Maria','La Molina','La Victoria','Lince','Las Palmeras','Chosica','Lurin','Los Almacigos','Rinconada del Puruhuay','Fundo Santa Genoveva','Los Maderos','Casco Viejo','Vista Alegre','Buena Vista Alta','Lomas Pucara','Fundo la Querencia','Magdalena del Mar','Pueblo Libre','Miraflores','Pachacamac','Puente Manchay','Tambo Inga','Pampa Flores','Manchay Alto Lote B','Invasion Cementerio','Manchay Bajo','Santa Rosa de Mal Paso','Cardal','Jatosisa','Tomina','Pucusana','Honda','Quipa','Los Pelicanos','Playa Puerto Bello','Ñaves','Granja Santa Elena','Alvatroz II','Poseidon - Lobo Varado','Playa Minka Mar','Playa Acantilado','Puente Piedra','Punta Hermosa','Capilla Lucumo','Cucuya','Pampapacta','Avicola San Cirilo de Loma Negra - 03','Avicola San Cirilo de Loma Negra - 02','Avicola San Cirilo de Loma Negra - 01','Pampa Mamay','Cerro Botija','Agricultores y Ganaderos','Pampa Malanche Avicola Puma','Punta Negra','Chancheria','Rimac','San Bartolo','Plantel 41','Granja 4','Granja 5','Granja 07','Granja 44','Granja 47','Santa Maria I','Las Torres Santa Fe','San Francisco de Borja','San Isidro','San Juan de Lurigancho','Ciudad de Dios','San Luis','Barrio Obrero Industrial','San Miguel','Santa Anita - los Ficus','Santa Maria del Mar','Don Bruno','Santa Rosa','Santiago de Surco','Surquillo','Villa el Salvador','Villa Maria del Triunfo', 'Pueblo libre']
# values
postal_code1 = [15001,15003,15004,15006,15018,15019,15046,15072,15079,15081,15082,15083,15088,15123,15004,15011,15012,15019,15022,15023,15026,15476,15479,15483,15487,15491,15494,15498,15047,15049,15063,15082,15083,15121,15122,15313,15316,15318,15319,15320,15321,15324,15320,15320,15320,15320,15320,15320,15121,15320,15320,15121,15320,15320,15121,15121,15122,15122,15121,15121,15121,15320,15320,15320,15320,15320,15320,15121,15121,15121,15320,15121,15319,15121,15121,15121,15320,15320,15121,15121,15121,15121,15320,15320,15320,15122,15122,15122,15122,15122,15122,15122,15122,15121,15121,15122,15122,15121,15121,15122,15122,15121,15122,15122,15122,15472,15476,15054,15056,15057,15058,15063,15064,15066,15067,15593,15594,15593,15593,15593,15593,15593,15593,15593,15311,15312,15313,15314,15316,15324,15326,15327,15328,15332,15003,15004,15006,15007,15008,15009,15011,15018,15022,15311,15328,15331,15332,15333,15046, 15001]

In [63]:
# Return a dictionarie
ct_pc = dict( zip( cities , postal_code1) )

In [64]:
ct_pc

{'Fray Martin': 15001,
 'Santa Rosa de Puquio': 15003,
 'Cuchicorral': 15004,
 'Santiago de Punchauca': 15006,
 'La Cruz (11 Amigos)': 15018,
 'Cerro Cañon': 15019,
 'Cabaña Suche': 15046,
 'San Lorenzo': 15122,
 'Jose Carlos Mariategui': 15079,
 'Pascal': 15081,
 'La Esperanza': 15082,
 'Fundo Pancha Paula': 15083,
 'Olfa': 15088,
 'Rio Seco': 15123,
 'Paraiso': 15004,
 'El Rosario': 15011,
 'Cerro Puquio': 15012,
 'La Campana': 15019,
 'Las Animas': 15022,
 'Vetancio': 15023,
 'Roma Alta': 15026,
 'San Jose': 15476,
 'San Pedro de Carabayllo': 15121,
 'Huacoy': 15483,
 'Fundo Pampa Libre': 15487,
 'Ex Fundo Santa Ines': 15491,
 'Reposo': 15494,
 'Carmelito': 15498,
 'Santa Elena': 15047,
 'Don Luis': 15049,
 'Santa Ines Parcela': 15063,
 'Asociacion Santa Ines': 15082,
 'Roma Baja': 15083,
 'Residencial Santa Lucia': 15121,
 'San Francisco': 15122,
 'Santa Margarita - Molinos': 15313,
 'Sipan Peru': 15316,
 'Fundo Cuadros': 15318,
 'Bello Horizonte': 15319,
 'El Hueco': 15320,
 'Ex F

## <a id='1.6'> 1.6 Arrays and Matrix  </a> 


In [48]:
import numpy as np

# A library is a collection of modules or a single module. Libraries are the tools we will use to make our program.

In [50]:
# 1D array (vector)  1 DIMENSION
a = np.array( [1, 2, 3, 4, 5] )
print(a)

[1 2 3 4 5]


In [69]:
type(a)

numpy.ndarray

In [51]:
np.mean(a)  #media de vector

3.0

Standar deviation in Python by default

\begin{equation}
 sd(x) = \sqrt{\frac{\sum(x_i-\bar{x})^2}{N-1}}
\end{equation}

In [52]:
np.std(a)  #desviacion N-1

1.4142135623730951

Standar deviation in Python 

\begin{equation}
 sd(x) = \sqrt{\frac{\sum(x_i-\bar{x})^2}{N}}
\end{equation}

In [53]:
np.std(a,ddof=1)  #desviacion N

1.5811388300841898

In [55]:
# 2D array    2 DIMENSIONES
M = np.array( [ [1, 2, 3], [4, 5, 6] ] )

print(M)

[[1 2 3]
 [4 5 6]]


In [77]:
# dimensiones   M.shape (filas, columnas) , cuenta 0

M.shape

(2, 3)

In [56]:
print("Rows :",M.shape[0],"\n", "Columns: ", M.shape[1])


Rows : 2 
 Columns:  3


In [57]:
# Create a 1D NumPy array with values from 0 to 20 (exclusively) incremented by 2:
y = np.arange( 0, 20, 2 )
print(y)

[ 0  2  4  6  8 10 12 14 16 18]


In [74]:
# deafult one by one ==> y = np.arange( 1, 11, 1)

y = np.arange( 1, 11)
print(y)

list(range(11))   #range(k) es lista de 0 hasta k-1

[ 1  2  3  4  5  6  7  8  9 10]


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [80]:
# rep() equivalent in python

print(np.repeat(2, 4))  # 2 se repite 4 veces
print(np.repeat(range(11), 4))  # el vector range(11) se repite 4 veces, en orden

print(np.tile(np.array([1,2]), 4)) # se repite [1,2] 4 veces, en orden de lista
print(np.tile(range(11),5))  # se repite [0,11] 5 veces, en orden de lista

# split array

print(np.array_split(np.arange(0,10),4))  # de [0,10] se agrupa en 4 grupos

[2 2 2 2]
[ 0  0  0  0  1  1  1  1  2  2  2  2  3  3  3  3  4  4  4  4  5  5  5  5
  6  6  6  6  7  7  7  7  8  8  8  8  9  9  9  9 10 10 10 10]
[1 2 1 2 1 2 1 2]
[ 0  1  2  3  4  5  6  7  8  9 10  0  1  2  3  4  5  6  7  8  9 10  0  1
  2  3  4  5  6  7  8  9 10  0  1  2  3  4  5  6  7  8  9 10  0  1  2  3
  4  5  6  7  8  9 10]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7]), array([8, 9])]


### Matrix

In [81]:
#cada elemento debe ser un vector
A = np.array([np.arange(0,10), np.arange(10,20), np.arange(30,40), np.arange(-20,-10), np.arange(2,21,2)])

In [82]:
A

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [-20, -19, -18, -17, -16, -15, -14, -13, -12, -11],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20]])

In [83]:
#Sacar filas
A[2:5,:]  # rows selecrtion


array([[ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [-20, -19, -18, -17, -16, -15, -14, -13, -12, -11],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20]])

In [84]:
#Sacar columnas
A[:,0:6]  # columns selecrtion

array([[  0,   1,   2,   3,   4,   5],
       [ 10,  11,  12,  13,  14,  15],
       [ 30,  31,  32,  33,  34,  35],
       [-20, -19, -18, -17, -16, -15],
       [  2,   4,   6,   8,  10,  12]])

In [85]:
M1 = np.zeros( (8, 2) )
print(M1)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [86]:
M2 = np.ones( (8, 4) )
print(M2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Join matrix

In [87]:
#Juntar matrices M1 + M2  con h (orizontal)

M3 = np.hstack((M1,M2))  # stack horizontal 
M3

array([[0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.]])

In [88]:
M4 = np.array([[2,2,3,4,5,1],[1,5,5,9,8,2]])
print(M4)

[[2 2 3 4 5 1]
 [1 5 5 9 8 2]]


In [89]:
M5 = np.vstack((M3,M4)) # stack vertical 
print(M5)
M5.T

[[0. 0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1.]
 [2. 2. 3. 4. 5. 1.]
 [1. 5. 5. 9. 8. 2.]]


array([[0., 0., 0., 0., 0., 0., 0., 0., 2., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 2., 5.],
       [1., 1., 1., 1., 1., 1., 1., 1., 3., 5.],
       [1., 1., 1., 1., 1., 1., 1., 1., 4., 9.],
       [1., 1., 1., 1., 1., 1., 1., 1., 5., 8.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 2.]])

In [90]:
# Create a 1D NumPy array of ones of length 10:
w = np.ones(10)
print(w)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [91]:
# Create the identity matrix of size 8:
I = np.eye(8)
print(I)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [92]:
I3 = I.reshape(32, 2)
print(I3)

[[1. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]]


In [90]:
random.seed(4)

np.random.rand(10)   #crea 10 valores aleatorios

array([0.83955418, 0.36695914, 0.04044813, 0.16880262, 0.50221557,
       0.71942654, 0.49558592, 0.17121426, 0.84532703, 0.33483598])

In [99]:
x1 = np.random.rand(5) 
x1

array([0.97013988, 0.14538263, 0.74926613, 0.42933554, 0.43022219])

In [100]:
#Aleatorios
import random 

random.seed(175)  #semilla aleatoria para producir números aleatorios

x1 = np.random.rand(500)      # 500 números de uniform distribution [0,1] =rand 
x2 = np.random.rand(500)      # uniform distribution [0,1]
x3 = np.random.rand(500)      # uniform distribution [0,1]
x4 = np.random.rand(500)      # uniform distribution [0,1]
e = np.random.normal(0,1,500) # normal distribution mean = 0 and sd = 1

# Poblacional regression (Data Generating Process GDP)


Y = 1 + 0.8*x1 + 1.2*x2 + 0.5*x3 + 1.5*x4 + e
Y

array([ 4.87863271,  1.56120431,  1.93359257,  3.67539287,  4.24659298,
        2.42295583,  2.56433658,  3.38087675,  2.70221932,  0.84180773,
        2.78529992,  2.25885783,  1.89039266,  4.17444822,  3.72032322,
        4.31786388,  6.15341893,  4.06729653,  3.89054804,  2.75583874,
        1.85709654,  1.54076242,  1.31768696,  4.57344863,  2.21486487,
        3.68497022,  3.23109349,  1.64733404,  4.62913755,  2.14417541,
        3.50228993,  4.81360049,  2.74837422,  2.54925761,  2.60733886,
        1.71553561,  2.88919481,  3.76714782,  5.108373  ,  2.09829862,
        4.88359563,  2.11485336,  2.28187848,  1.10237016,  4.04330409,
        2.26878173,  2.91063201,  2.62398586,  4.50301216,  3.21680876,
        3.931889  ,  3.59201718,  2.5095828 ,  2.5724093 ,  3.28696417,
        4.74278473,  1.92634039,  1.38217291,  5.12587886,  2.00161577,
        3.91788164,  5.67762989,  1.2602967 ,  3.31618619,  3.80837839,
        3.48127146,  3.83514999,  0.02176207,  1.74139258,  2.77

In [101]:
X = np.column_stack((np.ones(500),x1,x2,x3,x4))  #difernetes tamños de X
#juntar todo en una sola matriz
X

array([[1.        , 0.42065599, 0.7702674 , 0.46013913, 0.97209977],
       [1.        , 0.54306598, 0.34923081, 0.32033356, 0.85355502],
       [1.        , 0.03555558, 0.26934049, 0.88846397, 0.59526898],
       ...,
       [1.        , 0.73293105, 0.01222204, 0.18080452, 0.55615452],
       [1.        , 0.65842668, 0.22881853, 0.69012669, 0.11184282],
       [1.        , 0.1756457 , 0.72036714, 0.41167129, 0.0796391 ]])

In [102]:
beta = np.linalg.inv(X.T @ X) @ ((X.T) @ Y )

# inversa de una matriz
# multiplicar matriz @
print(beta)

[0.90137591 0.82888202 1.50221568 0.50139047 1.36575401]


# References

## Numpy 
https://numpy.org/doc/stable/reference/arrays.html

https://www.kaggle.com/code/hkumls/intensive-python-tutorial-numpy/notebook