#  Laboratorio 2 - Python
## @author: Roberto Mendoza 

## <a id='1.0'> 1.0 If statement </a> 

In [10]:
import random
import numpy as np
import math

#Ejercicio 1: evaluar es media de vector es >< que media

#1. generar vector de n1 a n2 con n elementos
    # np.random.randint(-n1, n2, n)  

y = np.random.randint(-10, 10, 10)
y   # vector 

if np.mean(y) > 0 :  
    
    dummy = 1
    
else :
    dummy = 0
        
print(dummy)

0


## <a id='1.1'> 1.1 Nested if statement </a> 

In [72]:
v = [2, np.nan, "String", False]
a = int(np.random.randint(0,4,1))
v = v[a]

#Ejercicio 2: evaluar si objeto de lista es de clase  ==> isinstance(objeto, nombre_clase) ==> evalua ==> True/False

if isinstance( v, int ):      # si se cumple, imprime
    print(v, " es numero entero (no missing)")
elif math.isnan(v):
    print(v, " es un missing")
elif isinstance( v, str ):
    print(v, " es un string") 
elif isinstance( v, bool ):
    print(v, " es un logical")     
else:
    print("Sin resultado")       
    

nan  es un missing


## <a id='1.1'> 1.? While </a> 
### If I have my savings today of S/.1,000.00. How much will my savings be worth in 10 years at an interest rate of 2.5%?

$$
    S_{y+1}	=S_{y}(1+i)
$$

In [73]:
#Ejercicio 3: interes compuesto

#  save
S = 1000
# Periods
n = 10
# interes rate
i = 0.025

year = 1
while year < n:
    S =  S * (1+i)
    year += 1
    print( year, S)

2 1025.0
3 1050.625
4 1076.890625
5 1103.812890625
6 1131.4082128906248
7 1159.6934182128903
8 1188.6857536682123
9 1218.4028975099175
10 1248.8629699476653


## <a id='1.2'> 1.2 While if statement </a> 

In [214]:
#Ejercicio 4: Aumentar salario condicionado a valor aleatorio se aproxime a 0 o 1
    #NOta, SÍ se imprime TODOS LOS VALORES
w = 10

while (w > 7  & w <= 15) :   #1. mientras que el salario está entre 7 y 15
      
    coin = round( np.random.uniform(0,1) ) # 1. se va a rendondear un numero aleatorio entre 0 y 1 (solo un numero)
  
    if coin == 1:          #2. luego, si ese numero se aproxima a 1 ==, se suma 2soles al salario
        w =  w + 2
    else :
        w = w - 10         #2. luego, si ese numero se aproxima a 0, restar 10 soles (no se ve) y mostrar salario
        print(w)             
                            #3. el valor de 'w' se pasa a while otra vez ==> #1.
                            #3. si falla a requisito de while ==> se muestra resultado de #2.

0


## <a id='1.3'> 1.3 For Loop </a> 

In [174]:
#Ejercicio 5: en el loop cada elemento del vector se evalúa por separado, todos los resultados se muestran

ages = np.array([21, 23, 25, 24, 20])   #vector

for age in ages:

    print(age+10 )  

31
33
35
34
30


In [180]:
#Ejercicio 6: 

for i in range(50):           #1. lista de 0 a 50-1=49
    if i in range(15,21) :       #2. si elemento de la lista está entre 15 y 20=21-1 mostrar: 
        None                         #2.a. 'nada'
    else :                       #2. en otro caso mostrar: 
        print("Ejecutanto",i,"\n")   #2.b.  frase con elemento  


# Example 2

for j in range(101):
    print(j)
    
    if j > 20:
        break               # se rompe toda la cadena que continua

Ejecutanto 0 

Ejecutanto 1 

Ejecutanto 2 

Ejecutanto 3 

Ejecutanto 4 

Ejecutanto 5 

Ejecutanto 6 

Ejecutanto 7 

Ejecutanto 8 

Ejecutanto 9 

Ejecutanto 10 

Ejecutanto 11 

Ejecutanto 12 

Ejecutanto 13 

Ejecutanto 14 

Ejecutanto 21 

Ejecutanto 22 

Ejecutanto 23 

Ejecutanto 24 

Ejecutanto 25 

Ejecutanto 26 

Ejecutanto 27 

Ejecutanto 28 

Ejecutanto 29 

Ejecutanto 30 

Ejecutanto 31 

Ejecutanto 32 

Ejecutanto 33 

Ejecutanto 34 

Ejecutanto 35 

Ejecutanto 36 

Ejecutanto 37 

Ejecutanto 38 

Ejecutanto 39 

Ejecutanto 40 

Ejecutanto 41 

Ejecutanto 42 

Ejecutanto 43 

Ejecutanto 44 

Ejecutanto 45 

Ejecutanto 46 

Ejecutanto 47 

Ejecutanto 48 

Ejecutanto 49 

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
20


## <a id='1.3'> 1.3 While + Break </a> 

In [197]:
#Ejercicio 7: Bucle infinito  == While True
    #el bucle continnuara imprimiendo hasta que el numero random 'coin' se aproxime a 1
w = 10

while True :
    coin = round( np.random.uniform(0,1) ) # redondear al entero más cercano
    if coin == 1 :
        break 
    else:
        w = w + 10
        print(w)

## <a id='1.4'> 1.4 Function </a> 

In [218]:
#1. fUNCION simple:
        # def nombre_funcion(x,y,z)
        #         f1(x,y,z)
        #         f2(x,y,z)
        #         f3(x,y,z)
                    
        #         output= (f1, f2, frase)
        
def calculator(x,y,z):
    result = x*y*z
    
    return result


##usando funcion definida:  ==> llamar nombre ==> colocar inputs (x,y,z...)
calculator( 158, 38, 10 ) 

60040

In [223]:
#2. funcion multiples outputs

def calculator_square( x, y ):
    
    x2 = x * x                            #operaciones (varias)
    y2 = y * y
    
    result = x2 * y2   
    
    return result, x2, f"La multiplicación del cuadrado es: {result}"    #resultados que se muestran al llamar a funcion


##usando funcion definida:  ==> llamar nombre ==> colocar inputs (x,y,z...)
print(calculator_square(3, 4) )      

##usando funcion definida:  ==> llamar nombre ==> colocar inputs (x,y,z) ==> seleccionar output específico a mostrar []
print( calculator_square(3, 4)[1] )
calculator_square(3, 4)[2]
                

(144, 9, 'La multiplicación del cuadrado es: 144')
9


'La multiplicación del cuadrado es: 144'

In [224]:
#3. funcion con statements

#### el resultado al llamar la funcion dependera del valor de las operaciones internas
def calculator_square_2( x, y ):
    
    x2 = x * x
    y2 = y * y
    
    result = x2 * y2   
    if result <= 200:
           return f"Large number. Get only the result variable {result}"
    else:
           return  print( "Too large number. Do not return variables!")


##usando funcion definida:  ==> llamar nombre ==> colocar inputs (x,y,z...)
calculator_square_2(300, 4)

Too large number. Do not return variables!


35

In [225]:
# 4. fUNCION CON 'y' tipo de variables FIJA

def calculator_base_5( x , y = 5 ):
    
    result = x * y
    
    return result

##usando funcion definida:  ==> llamar nombre ==> colocar inputs (x,z...), ojo: la variable FIJA NO SE COLOCA
calculator_base_5( 7 )

35

In [231]:
# 5. fUNCION con clases de elementos definidos  inputs -> outputs

def calculator_base_5( x : int, y : float ) -> float:
    
    if not isinstance( x , int ):                        #2. si x es False, mostrar: 
        raise TypeError( "X variable is not int type.")     #2.a. mostrar el tipo de error
        
    if not isinstance( y, float ):                      #2. si y es False, mostrar: 
        raise TypeError( "Y variable is not float type.")   #2.b. mostrar el tipo de error

    result_correct = x * y                                      #2. si x , y son True ==> operar, mostrar:
    return result_correct                                         #2.c. mostrar el resultado correcto


print(calculator_base_5( 8, 3.0 ))   #24

calculator_base_5( np.nan, 3.0)      #TypeError

24.0


TypeError: X variable is not int type.

In [247]:
#### 6. Function y valore predeterminados de parámetros

def transpose(M, est = True, z = None):
    
    if not isinstance( M , np.ndarray ) :       #2. Si M no es una Matriz  
        raise TypeError( "x must be a n-array")     #2.a mostrar error
  
    
    elif (est and (z is None) ) :               #2. Si est=True & z=None
                                                  #Operaciones:
        M = M.T                                   #transpuesta de M
        Z = np.zeros((M.shape[0], M.shape[1]))    #matriz de ceros Z, con igual filas y columnas que M
        for i in range(M.shape[1]):               #para cada elemento en el rango(numero_columnas) de 0 hasta num_col-1
    
            a = np.mean(M[:,i])                     #media para cada columna i
            b = np.std(M[:,i])                      #desviacion para cada columna i
            Z[:,i] = (M[:,i]-a)/b                   #reemplazar en Z la columna i con = (i - media) /desviacion
            
        return Z                                  #mostrar Z 
    
    elif not z is None:                         #2. Si z es un número
        
        M = M*z                                     #multiplicar M con z
        return M                                    #mostrar M
    
    else:
        print('no hay opcion')
        
A = np.array([np.arange(0,10), np.arange(10,20), np.arange(30,40), np.arange(-20,-10), np.arange(2,21,2)])
A

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [-20, -19, -18, -17, -16, -15, -14, -13, -12, -11],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20]])

In [251]:
print(transpose(A, est = True, z = None))

[[-1.5666989  -1.5666989  -1.5666989  -1.5666989  -1.5666989 ]
 [-1.21854359 -1.21854359 -1.21854359 -1.21854359 -1.21854359]
 [-0.87038828 -0.87038828 -0.87038828 -0.87038828 -0.87038828]
 [-0.52223297 -0.52223297 -0.52223297 -0.52223297 -0.52223297]
 [-0.17407766 -0.17407766 -0.17407766 -0.17407766 -0.17407766]
 [ 0.17407766  0.17407766  0.17407766  0.17407766  0.17407766]
 [ 0.52223297  0.52223297  0.52223297  0.52223297  0.52223297]
 [ 0.87038828  0.87038828  0.87038828  0.87038828  0.87038828]
 [ 1.21854359  1.21854359  1.21854359  1.21854359  1.21854359]
 [ 1.5666989   1.5666989   1.5666989   1.5666989   1.5666989 ]]


In [249]:
print(transpose(A, est = False, z = 2))

[[  0   2   4   6   8  10  12  14  16  18]
 [ 20  22  24  26  28  30  32  34  36  38]
 [ 60  62  64  66  68  70  72  74  76  78]
 [-40 -38 -36 -34 -32 -30 -28 -26 -24 -22]
 [  4   8  12  16  20  24  28  32  36  40]]


## <a id='1.5'> 1.5 Try and Exception </a> 

In [297]:
a = ["2", 2]
i=int(np.random.randint(0,1))
a=a[i]
print(i)
# caso 1

try:     
    
    print(a/7)   # Si No corre el código porque se detecta un error ==> sale el Except
    
except TypeError:
      print("El argumento  deberia ser un número")
    
# caso 2

try:
    
    print(a/7)
    
except Exception:
    a = np.nan
    print(a)

# caso 3

try:
    
    print(a/7)

except Exception:
    a = np.nan
    print(a)

finally:
    
    print("Esta parte siempre se ejecuta")


0
El argumento  deberia ser un número
nan
nan
Esta parte siempre se ejecuta


## <a id='1.5'> 1.6 *args </a> 


The special syntax **\*args** in function definitions in python is used to pass a variable number of arguments to a function. The object **\*args** is a **tuple** that contains all the arguments. When you build your code, you should consider **\*args** as a **tuple**.

In [298]:
#Ejercicio 7: con elementos tupla ==>   name_funcion(*tupla_name)

def calculator( *args ):
    
    print( f" args is a {type( args )} " )    #indicar que es una tupla  ==> siempre aparece
    
    # Get the first value
    result = args[ 0 ]                       #sacar el primer argumento = es un numero
    
    # Keep the rest of values
    args1 = args[ 1: ]                       #demás argumentos mantenerlos como tupla
    
    # multiply all elements
    for element in args1:                    #para los element' en la tupla: multiplicarlo por el result' incial y de ahí 
        result = result * element            #el result' cambiado es el producto
                                             #iniciar for de nuevo
    
    return result                            # return ==> es el resultado

calculator( 8, 9, 50, 40, 10, 1)


args is a <class 'tuple'>


1440000

### <a id='#1.7.'>1.7. Kwargs </a> 

The special syntax **\*kwargs** in function definitions in python is used to pass a keyworded, variable-length argument list. We use the name kwargs with the double star. The reason is because the double star allows us to pass through keyword arguments (and any number of them).

In [301]:
#Ejercio 8

def calculator( *list_vars, **kwargs):
    
    print( type( list_vars ) )                     #indicar que es una tupla  ==> siempre aparece
    print( type( kwargs ) )                         #indicar que es una diccionario  ==> siempre aparece
    
    if   ( kwargs[ 'function' ] == "media" ) :     #2. si la funcion albergada es == media, mostrar:
        
        result = np.mean( list_vars )                  #2.a. sacar media de tupla 
    
    elif ( kwargs[ 'function' ] == "adicion" ) :   #2. si la funcion albergada es == adicion, mostrar:

        result = sum(list_vars)                        #2.a. sacar suma de tupla
    else:
        raise ValueError( f"The function argument {kwargs[ 'function' ]} is not supported." )

    return result


#calculator( 4, 5, 6, 7, 8, function = "adicion" )

calculator( 4, 5, 6, 7, 8, function = "media" )

# calculator( 4, 5, 6, 7, 8, function = "inversa" )

<class 'tuple'>
<class 'dict'>


6.0

### <a id='#1.8.'>1.8 Class </a> 

A class is a user-defined blueprint or prototype from which objects are created. Classes provide a means of bundling data and functionality together. Creating a new class creates a new type of object, allowing new instances of that type to be made.

### <a id='#1.8.1.'>1.8.1. The Importance of Python Classes </a> 

Classes are a way to organize your code into generic, reusable peices. At their best they are generic blueprints for things that will be used over and over again with little modification. The original concept was inspired by independent biological systems or organism unique from other organisms by the set or collection of features (attributes) and abilities (methods).

Functions are great to use when data is central to the work being done. Classes are great when you need to represent a collection of attributes and methods that will be used over and over again in other places.

Generally if you find your self writing functions inside of functions you should consider writing a class instead. If you only have one function in a class then stick with just writing a function.



- Classes provide an easy way of keeping the data members and methods together in one place which helps in keeping the program more organized.
- Using classes also provides another functionality of this object-oriented programming paradigm, that is, inheritance.
- Classes also help in overriding any standard operator.
- Using classes provides the ability to reuse the code which makes the program more efficient.
- Grouping related functions and keeping them in one place (inside a class) provides a clean structure to the code which increases the readability of the program.

###  <a id='#5.2.2.'> 1.8.2. Defining a class </a> 
it is considered to be a good practice to include a brief description about the class to increase the readability and understandability of the code.

In [ ]:
class class_name:
    
    def __init__(self, parameter1, parameter2):
        None
        
## Atributos

### <a id='#5.2.3.'>  Attributes </a> 
A value associated with an object which is referenced by name using dotted expressions. For example, `np.size`.

### <a id='#5.2.5.'> Method </a>
A function which is defined inside a class body. If called as an attribute of an instance of that class, the method will get the instance object as its first argument (which is usually called self). See function and nested scope.

In [309]:
import numpy as np 

A = np.arange( 8, 25 )
print(A)
print(A.size)
A.shape
A.mean()
        
dir(A)    # list de atributo

[ 8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
17


['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [310]:
"""
Method 
A function which is defined inside a class body. 
If called as an attribute of an instance of that class,
 the method will get the instance object as its first argument (which is usually called self). 
 See function and nested scope.
"""

from sklearn import linear_model
print(dir(linear_model))   #lista de atributos

['ARDRegression', 'BayesianRidge', 'ElasticNet', 'ElasticNetCV', 'GammaRegressor', 'Hinge', 'Huber', 'HuberRegressor', 'Lars', 'LarsCV', 'Lasso', 'LassoCV', 'LassoLars', 'LassoLarsCV', 'LassoLarsIC', 'LinearRegression', 'Log', 'LogisticRegression', 'LogisticRegressionCV', 'ModifiedHuber', 'MultiTaskElasticNet', 'MultiTaskElasticNetCV', 'MultiTaskLasso', 'MultiTaskLassoCV', 'OrthogonalMatchingPursuit', 'OrthogonalMatchingPursuitCV', 'PassiveAggressiveClassifier', 'PassiveAggressiveRegressor', 'Perceptron', 'PoissonRegressor', 'QuantileRegressor', 'RANSACRegressor', 'Ridge', 'RidgeCV', 'RidgeClassifier', 'RidgeClassifierCV', 'SGDClassifier', 'SGDOneClassSVM', 'SGDRegressor', 'SquaredLoss', 'TheilSenRegressor', 'TweedieRegressor', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_base', '_bayes', '_cd_fast', '_coordinate_descent', '_glm', '_huber', '_least_angle', '_logistic', '_omp', '_passive_aggressive', '

In [328]:
#### __init__

class MyFirstClass:
    
    def __init__( self, name, age ):
        self.name = name
        self.age = age
    
    # best way to define a method
    def print_name_1( self ):
        print( f'I am { self.name }.' )
    
    # wrong way to define a method 
    def print_name_2():
        print( f'This is my { name }.' )
    
    
    # the worst way to call a parameter
    # we need to define them as attributes
    def print_name_3( self ):
        print( f'This is my { name }.' )
        

In [329]:
        
class MyFirstClass:
    
    def __init__( self, name, age, school ):
        self.name = name
        self.age = age
        self.school = school
    
    # how to define a method
    def print_name_1( self ):
        print( f'I am { self.name }.' )
    
    # other method
    def person_age( self ):
        print( f' I am { self.name } , I am { self.age } old. ' )
    
    # other method
    def person_school( self ):
        print( f' I am {self.name} , I study at {self.school}. ' )
      
    # wrong way to define a method 
    def print_name_2():
        print( f'This is my { name }.' )
    
    # the worst way to call a parameter
    # we need to define them as attributes
    def print_name_3( self ):
        print( f'This is my { name }.' )    

In [331]:
student = MyFirstClass( name = "Jose" , age = 22, school = "Saco Oliveros" )
print(student.name)
print(student.age)          # == student.age
print(student.school)

student.print_name_1()
                            # sale error: student.print_name_2()
student.person_age()
student.person_school()

Jose
22
Saco Oliveros
I am Jose.
 I am Jose , I am 22 old. 
 I am Jose , I study at Saco Oliveros. 


###  <a id='#5.2.2.'> 1.9 Loop replacement </a> 


In [332]:
#10. FUNCION LAMBDA:

# Función Lambda para calcular 
square = lambda x: x ** 2

print(square(3)) # = 9

# Funcion tradicional 
def square1(num):
  return num ** 2

print(square1(5)) # Resultado: 25

9
25


In [336]:
vector = list(np.arange(100))    #lista de 100 valores 

vector = np.arange(100)          #lista de 100 valores 

list( map( lambda x: x**2 , vector)   )         #map (funcion, lista de valores a los que se le aplicará la funcion)
     # a la lista de 100 valores se le aplicará la funcion x^2 ==> se crea lista de resultados

[0,
 1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400,
 441,
 484,
 529,
 576,
 625,
 676,
 729,
 784,
 841,
 900,
 961,
 1024,
 1089,
 1156,
 1225,
 1296,
 1369,
 1444,
 1521,
 1600,
 1681,
 1764,
 1849,
 1936,
 2025,
 2116,
 2209,
 2304,
 2401,
 2500,
 2601,
 2704,
 2809,
 2916,
 3025,
 3136,
 3249,
 3364,
 3481,
 3600,
 3721,
 3844,
 3969,
 4096,
 4225,
 4356,
 4489,
 4624,
 4761,
 4900,
 5041,
 5184,
 5329,
 5476,
 5625,
 5776,
 5929,
 6084,
 6241,
 6400,
 6561,
 6724,
 6889,
 7056,
 7225,
 7396,
 7569,
 7744,
 7921,
 8100,
 8281,
 8464,
 8649,
 8836,
 9025,
 9216,
 9409,
 9604,
 9801]

## PANDAS

In [338]:
import pandas as pd 

##1. CREAR DICCIONARIO

# list of name, degree, score

var1 = np.random.rand(50000)
var2 = np.arange(0,50000)      #numeros ordenados DE 0 A 50000-1=49999
var3 =  np.random.rand(50000)
  
# dictionary of lists 
dict = {'v1': var1, 'v2': var2, 'v3': var3} 
dict

{'v1': array([0.76209784, 0.01061185, 0.20752948, ..., 0.92438914, 0.18468508,
        0.45949253]),
 'v2': array([    0,     1,     2, ..., 49997, 49998, 49999]),
 'v3': array([8.58780432e-01, 8.32697070e-01, 2.94629096e-01, ...,
        7.19265767e-01, 8.08480051e-04, 1.84536067e-01])}

In [344]:
#2. CONVERTIRLO EN HOJA DE CALCULO

df = pd.DataFrame(dict)
df

v1     v2        v3
0      0.762098      0  0.858780
1      0.010612      1  0.832697
2      0.207529      2  0.294629
3      0.789049      3  0.661005
4      0.707556      4  0.134282
...         ...    ...       ...
49995  0.584889  49995  0.751622
49996  0.369572  49996  0.177458
49997  0.924389  49997  0.719266
49998  0.184685  49998  0.000808
49999  0.459493  49999  0.184536

[50000 rows x 3 columns]

In [357]:
# df.apply(np.sum, axis = 0)  # columna por columna 
# df.apply(np.sum, axis = 1)  # fila por fila

M = np.array( [ [1, 2, 3], [4, 5, 6] ] )
print(M)
print(np.sum(M, axis=0))   # suma de columnas |
print(np.sum(M, axis=1))   # suma de filas __


[[1 2 3]
 [4 5 6]]
[5 7 9]
[ 6 15]


In [ ]:
# Agregar una COlumna
df['nueva_var'] = df['v2'].apply(lambda x : x**99)
df.head()

In [ ]:
!pip install swifter

import swifter

df['nueva_var'] = df['v2'].swifter.apply(lambda x : x**99) # parallel procesing 
df

  Created wheel for swifter: filename=swifter-1.3.4-py3-none-any.whl size=16321 sha256=b73d56d50a8a5805b5125259187509e68a42a59ce603ffbddfcb23af0a5f9c5b
  Stored in directory: c:\users\acwe\appdata\local\pip\cache\wheels\2b\5e\f2\3931524f702ffd03309e96d35ee2fbf9c61c27377511ee8d4c
Successfully built swifter


###  <a id='#2.0.'> 2.0 OLS method </a> 

In [ ]:
from scipy.stats import t # t - student 

random.seed(175)

x1 = np.random.rand(500) # uniform distribution  [0,1]
x2 = np.random.rand(500) # uniform distribution [0,1]
x3 = np.random.rand(500) # uniform distribution [0,1]
x4 = np.random.rand(500) # uniform distribution [0,1]
e = np.random.normal(0,1,500) # normal distribution mean = 0 and sd = 1
z = np.random.rand(500)

# Poblacional regression (Data Generating Process GDP)

Y = 1 + 0.8*x1 + 1.2*x2 + 0.5*x3 + 1.5*x4 + e

X = np.column_stack((np.ones(500),x1,x2,x3,x4))

In [307]:
def ols(M,Y, standar = True, Pvalue = True , instrumento = None, index = None):

    if standar and Pvalue and (instrumento is None)  and (index is None) :     #2. si se cumple todo, mostrar
        
        beta = np.linalg.inv(X.T @ X) @ ((X.T) @ Y )                             #2.a. estimar beta
        
        y_est =  X @ beta                                                        #2.b. Y estimado 
        n = X.shape[0]                                                           #2.c. numero de observaciones
        k = X.shape[1] - 1                                                       #2.d. numeros de x - unos
        nk = n - k                                                               #2.e. grados de libertad
        
        
        #falta ver el lambda***********************
        sigma =  sum(list( map( lambda x: x**2 , Y - y_est)   )) / nk 
        Var = sigma*np.linalg.inv(X.T @ X)
        sd = np.sqrt( np.diag(Var) )  ## raíz cuadrado a los datos de la diagonal principal de Var
        t_est = np.absolute(beta/sd)
        pvalue = (1 - t.cdf(t_est, df=nk) ) * 2
        df = pd.DataFrame( {"OLS": beta , "standar_error" : sd ,
                                 "Pvalue" : pvalue})    

    
    elif (not instrumento is None) and (not index is None) :
        
        beta = np.linalg.inv(X.T @ X) @ ((X.T) @ Y )
        
        index = index  - 1 
        Z = X
        Z[:,index] = z ## reemplazamos la variable endógena por el instrumento en la matrix de covariables
        beta_x = np.linalg.inv(Z.T @ Z) @ ((Z.T) @ X[:,index] ) 
        x_est  = Z @ beta_x
        X[:,index] = x_est ## se reemplaza la variable x endógena por su estimado 
        beta_iv = np.linalg.inv(X.T @ X) @ ((X.T) @ Y )
        df = pd.DataFrame( {"OLS": beta , "OLS_IV" : beta_iv})  

    return df



ols(X,Y)

ols(X,Y,instrumento = z, index = 1)


OLS    OLS_IV
0  0.865902  0.456812
1  0.908194  1.199205
2  1.223719  1.523232
3  0.561198  0.887494
4  1.738741  2.020196